[theme]

# "dark" or "light" 
base = "dark"
#base = "light"

# Cor amarela escura para botões primários
primaryColor = "#DAA520"  # GoldenRod

# Cor marrom para botões secundários
secondaryBackgroundColor = "#8B4513"  # SaddleBrown

# Cor do texto
textColor = "#FFFFFF"  # Branco

font = "sans serif"